# Generated by Django 2.2.3 on 2019-07-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190704_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='headquarter',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is headquarter?'),
        ),
        migrations.DeleteModel(
            name='HeadQuarter',
        ),
    ]
