# Generated by Django 2.2.3 on 2019-07-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190704_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='headquarter',
            field=models.BooleanField(default=False, verbose_name='Is headquarter?'),
        ),
    ]
